# Private helper: strip the internal reasoning prefix that the OpenShift AI
# model sometimes prepends before a special "assistantfinal" marker.
# When the marker is absent, heuristically strip leading chain-of-thought
# lines (e.g. "We need to...", "Let's...", "So the...") and the "Answer:"
# prefix, then return whatever clean prose remains.
.parse_openshift_answer <- function(raw) {
  marker <- "assistantfinal"
  if (grepl(marker, raw, fixed = TRUE)) {
    return(trimws(strsplit(raw, marker, fixed = TRUE)[[1]][2]))
  }

  text <- trimws(raw)

  # Strip a leading "Answer:" prefix if present
  text <- sub("^Answer:\\s*", "", text)

  trimws(text)
}

#' Interpret Epidemiological Data or Visualisations using LLMs
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' 
#' This function interprets a given data frame or ggplot visualisation by sending it to a language model API. It supports multiple LLM providers, including an internal OpenShift AI deployment, allowing users to specify the desired provider and model through environment variables.
#'
#' @param input An input object, either a data frame or a ggplot object, representing the data or visualisation to be interpreted.
#' @param word_limit Integer. The desired word length for the response. Defaults to 100.
#' @param prompt_extension Character. Optional additional instructions to extend the standard prompt. Defaults to NULL.
#' @return A character string containing the narrative or interpretation of the input object as generated by the LLM.
#' @details
#' **Supported LLM Providers and Models:**
#' - **OpenAI**: Utilises OpenAI's models via `chat_openai()`. Requires setting the `OPENAI_API_KEY` environment variable. Applicable models include:
#'   - `"gpt-4.1-nano"`
#' - **Google Gemini**: Utilises Google's Gemini models via `chat_gemini()`. Requires setting the `GOOGLE_API_KEY` environment variable. Applicable models include:
#'   - `"gemini-2.5-flash-lite"`
#' - **Anthropic Claude**: Utilises Anthropic's Claude models via `chat_anthropic()`. Requires setting the `CLAUDE_API_KEY` environment variable. Applicable models include:
#'   - `"claude-sonnet-4-20250514"`
#' - **OpenShift AI (internal)**: Utilises an internally hosted LLM via a direct `httr2` call to the `/v1/completions` endpoint.
#'   Set `LLM_PROVIDER` to `"openshiftai-gpt-oss-120b"`. Applicable models include:
#'   - `"openshiftai-gpt-oss-120b"`
#'   Note: ggplot image input is **not** supported for this provider.
#'
#' **Environment Variables:**
#' - `LLM_PROVIDER`: Specifies the LLM provider ("openai", "gemini", "anthropic", or "openshiftai-gpt-oss-120b").
#' - `LLM_API_KEY`: The API key or Bearer token corresponding to the chosen provider.
#' - `LLM_MODEL`: The model identifier to use.
#' - `LLM_URL`: Base URL of the OpenShift AI endpoint. Required only when using the `"openshiftai-gpt-oss-120b"` provider.
#'
#' **Note:** Ensure that the appropriate environment variables are set before invoking this function. The function will throw an error if the specified provider is unsupported or if required environment variables are missing.
#'
#' @import ggplot2
#' @importFrom jsonlite toJSON
#' @import ellmer
#' @importFrom httr2 request req_headers req_body_json req_timeout req_perform resp_body_json
#' @importFrom lifecycle badge signal_stage
#' @export
#'
#' @section Tested Models:
#' As of April 2026, this function has been tested and verified to work with the following models:
#' - OpenAI: gpt-4.1-nano
#' - Anthropic: claude-sonnet-4-20250514  
#' - Google Gemini: gemini-2.5-flash-lite
#' - OpenShift AI (internal): openshiftai-gpt-oss-120b
#' 
#' Additional models may be tested in the future. Users can provide custom instructions
#' through the \code{prompt_extension} parameter for specialised analysis requirements.
llm_interpret <- function(input,
                          word_limit = 100,
                          prompt_extension = NULL) {
  lifecycle::signal_stage("experimental", "llm_interpret()")

  # Validate input parameters
  if (!is.numeric(word_limit) || word_limit <= 0) {
    stop("word_limit must be a positive number")
  }

  if (!is.null(prompt_extension) && !is.character(prompt_extension)) {
    stop("prompt_extension must be NULL or a character string")
  }

  # Check for required environment variables with informative messages
  tryCatch({
    provider <- Sys.getenv("LLM_PROVIDER")
    if (provider == "") {
      stop("LLM_PROVIDER environment variable is not set. ",
           "Please set it to one of: 'openai', 'gemini', 'anthropic', or ",
           "'openshiftai-gpt-oss-120b'")
    }

    api_key <- Sys.getenv("LLM_API_KEY")
    if (api_key == "") {
      stop("LLM_API_KEY environment variable is not set. ",
           sprintf("For %s, please set the appropriate API key.",
                   toupper(provider)))
    }

    model <- Sys.getenv("LLM_MODEL")
    if (model == "") {
      stop("LLM_MODEL environment variable is not set. ",
           sprintf("For %s, please set an appropriate model identifier.",
                   toupper(provider)))
    }

    # OpenShift AI requires the base URL of the hosted endpoint
    if (provider == "openshiftai-gpt-oss-120b") {
      llm_url <- Sys.getenv("LLM_URL")
      if (llm_url == "") {
        stop("LLM_URL environment variable is not set. ",
             "Set it to the base URL of your OpenShift AI endpoint.")
      }
    }
  }, error = function(e) {
    stop("Error checking environment variables: ", conditionMessage(e))
  })

  # For the OpenShift AI provider we bypass ellmer entirely and use httr2
  # directly (the endpoint exposes /v1/completions, not /v1/chat/completions).
  use_openshift <- provider == "openshiftai-gpt-oss-120b"

  # Initialize the chat client with error handling (ellmer providers only)
  chat <- if (!use_openshift) {
    tryCatch({
      switch(
        provider,
        "openai"    = chat_openai(model = model, api_key = api_key),
        "gemini"    = chat_google_gemini(model = model, api_key = api_key),
        "anthropic" = chat_anthropic(model = model, api_key = api_key),
        stop(sprintf("Unsupported LLM provider: '%s'", provider))
      )
    }, error = function(e) {
      stop("Failed to initialize chat client: ", conditionMessage(e))
    })
  } else {
    NULL
  }

  # Set the system prompt with error handling (ellmer providers only)
  if (!use_openshift) {
    tryCatch({
      chat$set_system_prompt(
        "You are a concise assistant focusing on epidemiologically relevant observations."
      )
    }, error = function(e) {
      stop("Failed to set system prompt: ", conditionMessage(e))
    })
  }

  # Define the standard prompt
  standard_prompt <- tryCatch({
    prompt <- paste(
      "Please provide an interpretation focusing on the most",
      "epidemiologically relevant observations in",
      word_limit,
      "words or fewer."
    )
    if (!is.null(prompt_extension)) {
      prompt <- paste(prompt, prompt_extension)
    }
    prompt
  }, error = function(e) {
    stop("Failed to construct prompt: ", conditionMessage(e))
  })

  # Process input based on type
  if (is.data.frame(input)) {
    if (nrow(input) == 0) {
      stop("Input data frame is empty")
    }

    # Convert data frame to JSON with error handling
    json_data <- tryCatch({
      jsonlite::toJSON(input, pretty = TRUE, auto_unbox = TRUE)
    }, error = function(e) {
      stop("Failed to convert data frame to JSON: ", conditionMessage(e))
    })

    # Send JSON data to the API with error handling
    if (use_openshift) {
      # Build prompt for the /v1/completions API. Do NOT mention word counts —
      # this model's chain-of-thought interprets any count target as an
      # instruction to literally count and annotate every word. Length is
      # controlled solely via max_tokens instead.
      # Build prompt for the /v1/completions API. This model works best with
      # the Question/Answer format (matching the proven Python RAG pattern).
      # The model emits chain-of-thought reasoning followed by an
      # "assistantfinal" marker; .parse_openshift_answer() strips that prefix.
      openshift_instruction <- paste0(
        "You are a concise epidemiological assistant.\n",
        "Answer the question using only the information in the data.\n",
        "Keep your answer short and helpful.\n",
        "Do not explain how you got the answer.\n",
        if (!is.null(prompt_extension)) paste0(prompt_extension, "\n") else "",
        "\nData:\n", json_data, "\n\n",
        "Question: Please provide a brief interpretation focusing on the ",
        "most epidemiologically relevant observations.\n\n",
        "Answer:"
      )
      full_prompt <- openshift_instruction
      llm_url <- Sys.getenv("LLM_URL")
      tryCatch({
        resp <- httr2::request(paste0(llm_url, "/v1/completions")) |>
          httr2::req_headers(
            Authorization = paste("Bearer", api_key)
          ) |>
          httr2::req_body_json(list(
            model       = model,
            prompt      = full_prompt,
            max_tokens  = max(300L, ceiling(word_limit * 3L)),
            temperature = 0.1
          )) |>
          httr2::req_timeout(60) |>
          httr2::req_perform()
        raw_text <- httr2::resp_body_json(resp)$choices[[1]]$text
        return(.parse_openshift_answer(raw_text))
      }, error = function(e) {
        stop("OpenShift AI API request failed: ", conditionMessage(e))
      })
    } else {
      tryCatch({
        response <- chat$chat(standard_prompt, json_data)
        return(response)
      }, error = function(e) {
        stop("API request failed for data frame input: ", conditionMessage(e))
      })
    }
  }
  else if (inherits(input, "ggplot")) {
    # The OpenShift AI endpoint (/v1/completions) is text-only and cannot
    # accept image data.
    if (use_openshift) {
      stop(
        "ggplot image input is not supported for the 'openshiftai-gpt-oss-120b' ",
        "provider. The internal endpoint only accepts text input. ",
        "Pass the underlying data frame instead."
      )
    }

    temp_file <- NULL

    # Use withCallingHandlers for cleanup even if error occurs
    withCallingHandlers({
      # Save the ggplot object as a temporary image
      temp_file <- tempfile(fileext = ".png")
      tryCatch({
        ggplot2::ggsave(
          temp_file,
          plot = input,
          width = 6,
          height = 4,
          dpi = 300
        )
      }, error = function(e) {
        stop("Failed to save plot as image: ", conditionMessage(e))
      })

      # Send image file to the API
      response <- tryCatch({
        chat$chat(content_image_file(temp_file), standard_prompt)
      }, error = function(e) {
        stop("API request failed for plot input: ", conditionMessage(e))
      })

      return(as.character(response))
    }, finally = {
      # Clean up temporary file
      if (!is.null(temp_file) && file.exists(temp_file)) {
        unlink(temp_file)
      }
    })
  }
  else {
    stop(
      sprintf(
        "Unsupported input type: %s. Input must be a data frame or ggplot object.",
        class(input)[1]
      )
    )
  }
}
